### ISSUE TITLE
getSharedInstance Error

### ISSUE THREAD

**Issue by Hassuunna** [mozkomor05/espo-call-recorder#1]
Hello David
I'm having a little problem running your code, after removing your company API part I'm trying to record call but it gives me an error

`if (recordingService == null) {
    recordingService = RecordingAccessibilityService.getSharedInstance();
      if (recordingService == null) {
        Toast.makeText(context, "CallRecord ERROR: make sure the accessibility service is enabled.", Toast.LENGTH_LONG).show();
          return;
    }
}`

that calling this bit

`    public static RecordingAccessibilityService getSharedInstance() {
        return instance;
    }
`

and this return always `null`

I tried turning getSharedInstance to synchronized but it didn't work also

Any help?

**Comment by mozkomor05** [comment]
Hi, thank you for opening issue,

Does the app fail only after removing the Espo API part? Does your version of Android support accessibility services, what version do you have? It seems like the `onServiceConnected` is never called. Did the app prompt you to enable accessibility service, if it did, make sure it stays enabled. E. g. I noticed accessibility service always disables when I reattach the debugger.

**Comment by Hassuunna** [comment]
Thanks for replying man

I can't try it with API because I don't have credentials so I don't know that
My version is Android 11
it supports accessibility services 
and it asked for it and I allow every time I debug
I worked this around by putting this before returning instance
`instance = new RecordingAccessibilityService();`

so current situation:
I managed to get the part where it records but after `Mediarecorder.stop();` I can't find the file recorded

**Comment by mozkomor05** [comment]
That is because the file is saved to /data/.../<com.app>/... directory accessible only for the application and system. Thus not visible in file manager without root access. See https://github.com/mozkomor05/espo-call-recorder/blob/7da00ceff9a1517c3f7d4bb84c30f12b05676a65/app/src/main/java/com/wpdistro/espocallrecorder/RecordingAccessibilityService.java#L97

There have been [huge storage permissions changes](https://developer.android.com/about/versions/11/privacy/storage) since Android 11. However, there are some public directories (such as Downloads, Documents) accessible the same way as before the upgrade. See https://stackoverflow.com/a/66317287
